replace yes command with echo 'y' in build workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,8 +33,9 @@ jobs:
       - name: Push build to GCP Artifact Registry
         run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/amarbot/amarbot:latest
 
+      # || true so the build doesn't fail if amarbot VM doesnt exist
       - name: Stop & deleted amarbot instance
-        run: yes | gcloud compute instances delete amarbot --zone us-central1-a
+        run: echo "y" | gcloud compute instances delete amarbot --zone us-central1-a || true
 
       - name: Create new amarbot instance
         run: |-
